[package]
name = "hyacinth"
version = "0.1.0"
edition = "2024"


[dependencies]
byteorder = "1.5.0"
chrono = "0.4.42"
delphinium = "1.0.0"
flate2 = "1.1.2"
percent-encoding = "2.3.2"
reqwest = "0.12.23"
sha2 = "0.10.9"
tokio = "1.47.1"
